create or replace 
TRIGGER BTAGP.TRG_SET_NLS_ENVIRONMENT
AFTER LOGON
ON BTAGP.SCHEMA
BEGIN
  EXECUTE IMMEDIATE 'ALTER SESSION SET "_mv_refresh_use_hash_sj"=false';
  EXECUTE IMMEDIATE 'ALTER SESSION SET nls_sort=''BINARY_CI''';
  EXECUTE IMMEDIATE 'ALTER SESSION SET nls_comp=''LINGUISTIC''';
  EXECUTE IMMEDIATE 'ALTER SESSION SET nls_timestamp_format=''YYYY-MM-DD HH24:MI:SS.FF2''';
  EXECUTE IMMEDIATE 'ALTER SESSION SET nls_date_format=''YYYY-MM-DD HH24:MI:SS''';
  EXECUTE IMMEDIATE 'ALTER SESSION SET NLS_TIMESTAMP_TZ_FORMAT=''YYYY-MM-DD HH24:MI:SSXFF TZR''';
END;
/

create or replace 
TRIGGER RW_AGP.TRG_SET_NLS_ENVIRONMENT
AFTER LOGON
ON RW_AGP.SCHEMA
BEGIN
  EXECUTE IMMEDIATE 'ALTER SESSION SET "_mv_refresh_use_hash_sj"=false';
  EXECUTE IMMEDIATE 'ALTER SESSION SET nls_sort=''BINARY_CI''';
  EXECUTE IMMEDIATE 'ALTER SESSION SET nls_comp=''LINGUISTIC''';
  EXECUTE IMMEDIATE 'ALTER SESSION SET nls_timestamp_format=''YYYY-MM-DD HH24:MI:SS.FF2''';
  EXECUTE IMMEDIATE 'ALTER SESSION SET nls_date_format=''YYYY-MM-DD HH24:MI:SS''';
  EXECUTE IMMEDIATE 'ALTER SESSION SET NLS_TIMESTAMP_TZ_FORMAT=''YYYY-MM-DD HH24:MI:SSXFF TZR''';
END;
/