SELECT REASON
, TO_CHAR(CREATION_TIME,'dd-mon-yyy hh24:mi:ss') ctime
, TO_CHAR(TIME_SUGGESTED,'dd-mon-yyy hh24:mi:ss') rtime
FROM DBA_ALERT_HISTORY
WHERE OBJECT_TYPE = 'TABLESPACE'
AND UPPER(RESOLUTION) = 'CLEARED'
ORDER BY CREATION_TIME ASC
;