RUN
{
  ALLOCATE CHANNEL disk1 DEVICE TYPE DISK FORMAT '/export/bkp_%U.rman'; 
  ALLOCATE CHANNEL disk2 DEVICE TYPE DISK FORMAT '/export/bkp_%U.rman'; 
  BACKUP AS COMPRESSED BACKUPSET DATABASE;
  release CHANNEL disk1;
  release CHANNEL disk2;
}



SELECT SID, SERIAL#, CONTEXT, SOFAR, TOTALWORK,
       ROUND(SOFAR/TOTALWORK*100,2) "%_COMPLETE"
FROM   V$SESSION_LONGOPS
WHERE  OPNAME LIKE 'RMAN%'
AND    OPNAME NOT LIKE '%aggregate%'
AND    TOTALWORK != 0
AND    SOFAR <> TOTALWORK;