SET ECHO OFF
SET HEADING OFF
SET FEEDBACK OFF
SET VERIFY OFF
SET PAGESIZE 1000
SPOOL tmp/drop_constraints.sql

SELECT 'ALTER TABLE '||owner||'.'||TABLE_NAME||' DISABLE CONSTRAINT '||CONSTRAINT_NAME||';'
FROM   DBA_CONSTRAINTS
WHERE  OWNER = upper('&1');

SELECT 'ALTER table '||owner||'.'||TABLE_NAME||' DROP CONSTRAINT '||CONSTRAINT_NAME||';' 
FROM DBA_CONSTRAINTS
WHERE  OWNER = upper('&1');

SPOOL OFF
SET VERIFY ON
SET FEEDBACK ON
SET HEADING ON
SET ECHO OFF
prompt tmp/drop_constraints.sql