set long 500000
COL SQL_TEXT FORMAT A90

SELECT OPTIMIZER_COST, EXECUTIONS, ST.SQL_TEXT
            FROM V$SQLTEXT ST, V$SQL SQ
            WHERE   SQ.ADDRESS ='&ADDR_SQL' AND
            ST.ADDRESS = SQ.ADDRESS
            ORDER BY ST.PIECE
/

