col DATABASE for a60
col "BACKUP STATUS" a12
col "START TIME" for a20
col "END TIME" for a20
col "BYTES" for a10
SELECT 
	C.MEMBER_TARGET_NAME AS "DATABASE", 
	H.STATUS AS "BACKUP STATUS", 
	max(H.START_TIME) AS "START TIME", 
	max(H.END_TIME) AS "END TIME", 
	max(H.OUTPUT_BYTES_DISPLAY) AS "BYTES"
FROM MGMT$TARGET T, MGMT$HA_BACKUP H, MGMT$TARGET_COMPOSITE C, MGMT$TARGET TC
WHERE  TC.TARGET_NAME = C.COMPOSITE_NAME
AND T.TARGET_NAME = C.MEMBER_TARGET_NAME
AND H.TARGET_GUID = T.TARGET_GUID
group by 
	C.MEMBER_TARGET_NAME, 
	H.STATUS
order by 1;

col DATABASE clear
col "BACKUP STATUS" clear
col "START TIME" clear
col "END TIME" clear
col "BYTES" clear