-- create role
CREATE ROLE RL_OEM_MONITOR;

GRANT SELECT_CATALOG_ROLE TO RL_OEM_MONITOR;
grant SELECT ANY DICTIONARY to RL_OEM_MONITOR; 
GRANT EXECUTE ON SYS.DBMS_MONITOR TO RL_OEM_MONITOR;
GRANT EXECUTE ON SYS.DBMS_SERVER_ALERT TO RL_OEM_MONITOR;
GRANT EXECUTE ON SYS.DBMS_WORKLOAD_REPOSITORY TO RL_OEM_MONITOR;



-- grant role
GRANT RL_OEM_MONITOR TO J10246;
GRANT RL_OEM_MONITOR TO J10223; 
GRANT RL_OEM_MONITOR TO J10252; 
GRANT RL_OEM_MONITOR TO J10227;


-- create user
CREATE USER TT0626
IDENTIFIED BY sdflsdkjflasdkjaslhsdklfh
PASSWORD EXPIRE
DEFAULT TABLESPACE TAB_USER
TEMPORARY TABLESPACE TEMP_USER
PROFILE PROF_USER;

GRANT RL_PPAGO TO TT0626;
GRANT RL_USER TO TT0626;
GRANT RL_OEM_MONITOR TO TT0626;

ALTER USER TT0626 QUOTA UNLIMITED ON TAB_USER;
ALTER USER TT0626 DEFAULT ROLE ALL;

