SET LONGCHUNKSIZE 1000000
--SET LINESIZE 1000
--SET PAGESIZE 0
SET TRIM ON
SET TRIMSPOOL ON
SET ECHO OFF
--SET LONG 1000000 
SET FEEDBACK OFF

spool ./output/SQL_REPORT_&1.txt
SELECT DBMS_SQLTUNE.report_sql_monitor(sql_id =>'&1',type=> 'TEXT')
AS report FROM dual;
spool off

--SET PAGESIZE 1000
SET TRIM OFF
SET TRIMSPOOL OFF
SET ECHO ON
--SET LONG 1000000 
SET FEEDBACK ON