CREATE USER OEM_OPER_USER
IDENTIFIED BY 123456
DEFAULT TABLESPACE TBS_ESI_GIIT 
ACCOUNT UNLOCK;

GRANT CONNECT TO OEM_OPER_USER;
GRANT OEM_MONITOR to OEM_OPER_USER;
grant alter user to OEM_OPER_USER;

